#!/bin/bash

cd $(mktemp -d) || exit 1

mkdir -p usr etc root proc dev/pts
ln -s usr/bin bin
ln -s usr/sbin sbin

mount --bind /nix/var/nix/profiles/default usr
mount --bind /proc proc
mount --bind /dev dev
mount --bind /dev/pts dev/pts

echo 'root:x:0:0:root:/root:/bin/bash' > etc/passwd
echo 'root:x:0:' > /etc/group
echo 'http://nixos.org/channels/nixpkgs-unstable nixpkgs' > root/.nix-channels

echo 'nixbld:x:30000:30000:Nix build user:/var/empty:/noshell' >> etc/passwd
echo 'nixbld:!:30000:nixbld' >> etc/group

chroot . nix-channel --update


